/// seq_miles_wait_leader()

if (sequence_position(0))
{
    sprite_index = spr_miles_wait_leader;
    image_index = 0;
    player_set_radii(6, 14, 3);
    hitbox_set_hurtbox(6, 10, 6, 16);
    hitbox_set_attackbox();
}
else if (sequence_position(3)) image_index = 1;
else if (sequence_position(9)) image_index = 2;
else if (sequence_position(12)) image_index = 3;
else if (sequence_position(15)) image_index = 4;
else if (sequence_position(18)) image_index = 5;
else if (sequence_position(21)) image_index = 6;
else if (sequence_position(24)) image_index = 7;
else if (sequence_position(27)) image_index = 8;
else if (sequence_position(39)) image_index = 9;
else if (sequence_position(47)) image_index = 10;
else if (sequence_position(55)) image_index = 11;
else if (sequence_position(63)) image_index = 12;
else if (sequence_position(71)) image_index = 13;
else if (sequence_position(81)) image_index = 14;
else if (sequence_position(89)) image_index = 15;
else if (sequence_position(97)) image_index = 16;
else if (sequence_position(105)) image_index = 17;
else if (sequence_position(115)) image_index = 18;
else if (sequence_position(123)) image_index = 19;
else if (sequence_position(131)) image_index = 20;
else if (sequence_position(139)) image_index = 21;
else if (sequence_position(149)) image_index = 22;
else if (sequence_position(157)) image_index = 23;
else if (sequence_position(165)) image_index = 24;
else if (sequence_position(173)) image_index = 25;
else if (sequence_position(183)) image_index = 26;
else if (sequence_position(191)) image_index = 27;
else if (sequence_position(199)) image_index = 28;
else if (sequence_position(209)) image_index = 29;
else if (sequence_position(217)) image_index = 30;
else if (sequence_position(225)) image_index = 31;
else if (sequence_position(233)) image_index = 32;
else if (sequence_position(241)) image_index = 33;
else if (sequence_position(249)) image_index = 34;
else if (sequence_position(257)) image_index = 35;
else if (sequence_position(265)) image_index = 36;
else if (sequence_position(273)) image_index = 37;
else if (sequence_position(281)) image_index = 38;
else if (sequence_position(289)) image_index = 39;
else if (sequence_position(297)) image_index = 40;
else if (sequence_position(305)) image_index = 41;
else if (sequence_position(313)) image_index = 42;
else if (sequence_position(321)) image_index = 43;
else if (sequence_position(329)) image_index = 44;
else if (sequence_position(337)) image_index = 45;
else if (sequence_position(345)) image_index = 46;
else if (sequence_position(353)) image_index = 47;
else if (sequence_position(361)) image_index = 48;
else if (sequence_position(369)) image_index = 49;
else if (sequence_position(379)) image_index = 50;
else if (sequence_position(386)) sequence_moment = 55;