/// seq_miles_wait_partner()

if (sequence_position(0))
{
    sprite_index = spr_miles_wait_partner;
    image_index = 0;
    player_set_radii(6, 14, 3);
    hitbox_set_hurtbox(6, 10, 6, 16);
    hitbox_set_attackbox();
}
else if (sequence_position(4)) image_index = 1;
else if (sequence_position(8)) image_index = 2;
else if (sequence_position(12)) image_index = 3;
else if (sequence_position(22)) image_index = 4;
else if (sequence_position(28)) image_index = 5;
else if (sequence_position(34)) image_index = 6;
else if (sequence_position(40)) image_index = 7;
else if (sequence_position(46)) image_index = 8;
else if (sequence_position(52)) image_index = 9;
else if (sequence_position(58)) image_index = 10;
else if (sequence_position(65)) image_index = 11;
else if (sequence_position(75)) image_index = 12;
else if (sequence_position(83)) image_index = 13;
else if (sequence_position(91)) image_index = 14;
else if (sequence_position(99)) image_index = 15;
else if (sequence_position(107)) image_index = 16;
else if (sequence_position(115)) image_index = 17;
else if (sequence_position(123)) image_index = 18;
else if (sequence_position(131)) image_index = 19;
else if (sequence_position(139)) image_index = 20;
else if (sequence_position(147)) image_index = 21;
else if (sequence_position(155)) image_index = 22;
else if (sequence_position(163)) image_index = 23;
else if (sequence_position(171)) image_index = 24;
else if (sequence_position(179)) image_index = 25;
else if (sequence_position(187)) image_index = 26;
else if (sequence_position(195)) image_index = 27;
else if (sequence_position(203)) image_index = 28;
else if (sequence_position(211)) image_index = 29;
else if (sequence_position(219)) image_index = 30;
else if (sequence_position(227)) image_index = 31;
else if (sequence_position(235)) image_index = 32;
else if (sequence_position(243)) image_index = 33;
else if (sequence_position(251)) image_index = 34;
else if (sequence_position(259)) image_index = 35;
else if (sequence_position(267)) image_index = 36;
else if (sequence_position(275)) image_index = 37;
else if (sequence_position(283)) image_index = 38;
else if (sequence_position(291)) image_index = 39;
else if (sequence_position(299)) image_index = 40;
else if (sequence_position(305)) image_index = 41;
else if (sequence_position(311)) image_index = 42;
else if (sequence_position(317)) image_index = 43;
else if (sequence_position(323)) image_index = 44;
else if (sequence_position(329)) image_index = 45;
else if (sequence_position(335)) image_index = 46;
else if (sequence_position(341)) image_index = 47;
else if (sequence_position(347)) image_index = 48;
else if (sequence_position(353)) image_index = 49;
else if (sequence_position(359)) image_index = 50;
else if (sequence_position(365)) image_index = 51;
else if (sequence_position(371)) image_index = 52;
else if (sequence_position(377)) image_index = 53;
else if (sequence_position(383)) image_index = 54;
else if (sequence_position(389)) image_index = 55;
else if (sequence_position(395)) image_index = 56;
else if (sequence_position(401)) image_index = 57;
else if (sequence_position(407)) image_index = 58;
else if (sequence_position(413)) image_index = 59;
else if (sequence_position(419)) image_index = 60;
else if (sequence_position(425)) image_index = 61;
else if (sequence_position(430)) sequence_moment = 383;