/// animation_init_sonic()

animation_add(CHAR_SONIC, "stand", seq_sonic_stand); //,     tml_sonic_idle_tag);
animation_add(CHAR_SONIC, "cliff_front", seq_sonic_cliff_front);
animation_add(CHAR_SONIC, "cliff_back", seq_sonic_cliff_back);
animation_add(CHAR_SONIC, "wait", seq_sonic_wait_leader, seq_sonic_wait_partner);
animation_add(CHAR_SONIC, "standby", seq_sonic_standby);
animation_add(CHAR_SONIC, "land", seq_sonic_land);
animation_add(CHAR_SONIC, "omochao", seq_sonic_omochao);
animation_add(CHAR_SONIC, "omochao_end", seq_sonic_omochao_end);
animation_add(CHAR_SONIC, "turn", seq_sonic_turn) //,      tml_sonic_turn_tag);
animation_add(CHAR_SONIC, "turn_brake", seq_sonic_turn_brake);
animation_add(CHAR_SONIC, "run_1", seq_sonic_run_1) //      tml_sonic_walk_tag);
animation_add(CHAR_SONIC, "run_2", seq_sonic_run_2) // tml_sonic_walk_fast_tag);
animation_add(CHAR_SONIC, "run_3", seq_sonic_run_3) //,       tml_sonic_jog_tag);
animation_add(CHAR_SONIC, "run_4", seq_sonic_run_4);
animation_add(CHAR_SONIC, "run_5", seq_sonic_run_5);
animation_add(CHAR_SONIC, "run_6", seq_sonic_run_6);
animation_add(CHAR_SONIC, "look", seq_sonic_look);
animation_add(CHAR_SONIC, "look_end", seq_sonic_look_end);
animation_add(CHAR_SONIC, "crouch", seq_sonic_crouch);
animation_add(CHAR_SONIC, "crouch_end", seq_sonic_crouch_end);
animation_add(CHAR_SONIC, "spin_dash", seq_sonic_spin_dash);
animation_add(CHAR_SONIC, "spin_charge", seq_sonic_spin_charge);
animation_add(CHAR_SONIC, "roll", seq_sonic_roll);
animation_add(CHAR_SONIC, "spin_flight", seq_sonic_spin_flight);
animation_add(CHAR_SONIC, "spin_fall", seq_sonic_spin_fall);
animation_add(CHAR_SONIC, "brake", seq_sonic_brake);
animation_add(CHAR_SONIC, "brake_fast", seq_sonic_brake_fast);
animation_add(CHAR_SONIC, "hurt", seq_sonic_hurt);
animation_add(CHAR_SONIC, "death", seq_sonic_death);
animation_add(CHAR_SONIC, "push", seq_sonic_push);
animation_add(CHAR_SONIC, "ramp_flight", seq_sonic_ramp_flight);
animation_add(CHAR_SONIC, "ramp_fall", seq_sonic_ramp_fall);
animation_add(CHAR_SONIC, "spring_flight", seq_sonic_spring_flight);
animation_add(CHAR_SONIC, "spring_fall", seq_sonic_spring_fall);
animation_add(CHAR_SONIC, "rail", seq_sonic_rail);
animation_add(CHAR_SONIC, "breathe", seq_sonic_breathe);
animation_add(CHAR_SONIC, "goal", seq_sonic_stand);
animation_add(CHAR_SONIC, "hammer", seq_sonic_hammer);
animation_add(CHAR_SONIC, "insta", seq_sonic_insta);
animation_add(CHAR_SONIC, "somersault", seq_sonic_somersault);
animation_add(CHAR_SONIC, "skid", seq_sonic_skid);
animation_add(CHAR_SONIC, "skid_end", seq_sonic_skid_end);
animation_add(CHAR_SONIC, "air_dash", seq_sonic_air_dash);
animation_add(CHAR_SONIC, "stomp", seq_sonic_stomp);
animation_add(CHAR_SONIC, "stomp_land", seq_sonic_stomp_land);
animation_add(CHAR_SONIC, "peel_out", seq_sonic_peel_out);
