/// animation_init_sonic()

animation_add(CHAR_SONIC, "stand", sequence_sonic_stand); //,     tml_sonic_idle_tag);
animation_add(CHAR_SONIC, "cliff_front", sequence_sonic_cliff_front);
animation_add(CHAR_SONIC, "cliff_back", sequence_sonic_cliff_back);
animation_add(CHAR_SONIC, "wait", sequence_sonic_wait_leader, sequence_sonic_wait_partner);
animation_add(CHAR_SONIC, "standby", sequence_sonic_standby);
animation_add(CHAR_SONIC, "land", sequence_sonic_land);
animation_add(CHAR_SONIC, "omochao", sequence_sonic_omochao);
animation_add(CHAR_SONIC, "omochao_end", sequence_sonic_omochao_end);
animation_add(CHAR_SONIC, "turn", sequence_sonic_turn) //,      tml_sonic_turn_tag);
animation_add(CHAR_SONIC, "turn_brake", sequence_sonic_turn_brake);
animation_add(CHAR_SONIC, "run_0", sequence_sonic_run_0) //      tml_sonic_walk_tag);
animation_add(CHAR_SONIC, "run_1", sequence_sonic_run_1) // tml_sonic_walk_fast_tag);
animation_add(CHAR_SONIC, "run_2", sequence_sonic_run_2) //,       tml_sonic_jog_tag);
animation_add(CHAR_SONIC, "run_3", sequence_sonic_run_3);
animation_add(CHAR_SONIC, "run_4", sequence_sonic_run_4);
animation_add(CHAR_SONIC, "run_5", sequence_sonic_run_5);
animation_add(CHAR_SONIC, "look", sequence_sonic_look);
animation_add(CHAR_SONIC, "look_end", sequence_sonic_look_end);
animation_add(CHAR_SONIC, "crouch", sequence_sonic_crouch);
animation_add(CHAR_SONIC, "crouch_end", sequence_sonic_crouch_end);
animation_add(CHAR_SONIC, "spin_dash", sequence_sonic_spin_dash);
animation_add(CHAR_SONIC, "spin_charge", sequence_sonic_spin_charge);
animation_add(CHAR_SONIC, "spin", sequence_sonic_roll, sequence_sonic_spin_flight, sequence_sonic_spin_fall);
animation_add(CHAR_SONIC, "brake", sequence_sonic_brake);
animation_add(CHAR_SONIC, "brake_fast", sequence_sonic_brake_fast);
animation_add(CHAR_SONIC, "hurt", sequence_sonic_hurt);
animation_add(CHAR_SONIC, "death", sequence_sonic_death);
animation_add(CHAR_SONIC, "push", sequence_sonic_push);
animation_add(CHAR_SONIC, "ramp_flight", sequence_sonic_ramp_flight);
animation_add(CHAR_SONIC, "ramp_fall", sequence_sonic_ramp_fall);
animation_add(CHAR_SONIC, "spring_flight", sequence_sonic_spring_flight);
animation_add(CHAR_SONIC, "spring_fall", sequence_sonic_spring_fall);
animation_add(CHAR_SONIC, "breathe", sequence_sonic_breathe);
animation_add(CHAR_SONIC, "goal", sequence_sonic_stand);
animation_add(CHAR_SONIC, "hammer", sequence_sonic_hammer);
animation_add(CHAR_SONIC, "insta", sequence_sonic_insta);
animation_add(CHAR_SONIC, "somersault", sequence_sonic_somersault);
animation_add(CHAR_SONIC, "skid", sequence_sonic_skid);
animation_add(CHAR_SONIC, "skid_end", sequence_sonic_skid_end);
animation_add(CHAR_SONIC, "air_dash", sequence_sonic_air_dash);
animation_add(CHAR_SONIC, "stomp", sequence_sonic_stomp);
animation_add(CHAR_SONIC, "stomp_land", sequence_sonic_stomp_land);
animation_add(CHAR_SONIC, "peel_out", sequence_sonic_peel_out);
