/// debug_menu_keyboard()

debug_add_option(debug_option_input_up);
debug_add_option(debug_option_input_down);
debug_add_option(debug_option_input_left);
debug_add_option(debug_option_input_right);
debug_add_option(debug_option_input_jump);
debug_add_option(debug_option_input_aux);
debug_add_option(debug_option_input_swap);
debug_add_option(debug_option_input_super);
debug_add_option(debug_option_input_tag);
debug_add_option(debug_option_input_alt);
debug_add_option(debug_option_input_start);
debug_add_option(debug_option_input_select);
debug_add_option(debug_option_input_confirm);
debug_add_option(debug_option_input_cancel);
debug_add_option(debug_option_input_log);
debug_add_option(debug_option_input_hide);
debug_add_option(debug_option_input_reset);
